fun f() {
    try {
    } catch (val e: Exception) {
    }

    try {
    } catch (var e: Exception) {
    }

    try {
    } catch (e: Exception) {
    }
}